//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoveWork17
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoTable
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string NAME { get; set; }
        public string LASTNAME { get; set; }
        public string NUMBER { get; set; }
        public string EMAIL { get; set; }
    }
}
